name: Build Qt App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y qtbase5-dev qttools5-dev qttools5-dev-tools build-essential cmake

    - name: Configure with CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build the app
      run: cmake --build build --config Release

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: qt-hello-button
        path: build/qt_hello_button_qt5
